"""Mock ACC API responses for practice exercises.

These mirror the real ACC API JSON structures so you can practice
parsing, transforming, and handling data without live credentials.
"""

# --- Authentication ---
AUTH_TOKEN_RESPONSE = {
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.mock_token_here",
    "token_type": "Bearer",
    "expires_in": 3600,
    "refresh_token": "mock_refresh_token_abc123xyz",
}

# --- Projects / Hubs ---
HUBS_RESPONSE = {
    "jsonapi": {"version": "1.0"},
    "data": [
        {
            "type": "hubs",
            "id": "b.abc123-def456",
            "attributes": {
                "name": "ACME Construction Company",
                "region": "US",
                "extension": {
                    "type": "hubs:autodesk.bim360:Account",
                    "version": "1.0",
                    "data": {},
                },
            },
        }
    ],
}

PROJECTS_RESPONSE = {
    "jsonapi": {"version": "1.0"},
    "data": [
        {
            "type": "projects",
            "id": "b.project-001",
            "attributes": {
                "name": "Highway Bridge Reconstruction",
                "scopes": ["b.project-001"],
                "extension": {
                    "type": "projects:autodesk.bim360:Project",
                    "version": "1.0",
                },
            },
        },
        {
            "type": "projects",
            "id": "b.project-002",
            "attributes": {
                "name": "Downtown Office Tower",
                "scopes": ["b.project-002"],
                "extension": {
                    "type": "projects:autodesk.bim360:Project",
                    "version": "1.0",
                },
            },
        },
    ],
}

# --- RFIs ---
RFIS_SEARCH_RESPONSE = {
    "pagination": {
        "limit": 100,
        "offset": 0,
        "totalResults": 5,
    },
    "results": [
        {
            "id": "rfi-001-abc",
            "title": "Concrete Mix Design Clarification",
            "rfiType": "Design",
            "assignedTo": "John Smith",
            "question": "Please clarify the concrete mix design for foundation piers. The spec calls for 5000 PSI but the drawings show 4000 PSI.",
            "suggestedAnswer": "Use 5000 PSI as per specification Section 03300.",
            "location": {"name": "Zone A - Foundation", "details": "Grid Line 3-5, Pier P-12"},
            "status": "Open",
            "officialResponse": None,
            "dueDate": "2025-04-15T00:00:00.000Z",
            "costImpact": "No",
            "scheduleImpact": "Yes",
            "priority": "High",
            "discipline": "Structural",
            "category": "Design Clarification",
            "externalId": "RFI-2025-001",
            "createdBy": "Mike Johnson",
            "createdAt": "2025-03-01T10:30:00.000Z",
            "updatedAt": "2025-03-20T14:00:00.000Z",
            "closedAt": None,
            "postedToDrawings": False,
            "companyName": "ACME Builders",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
            "permittedActions": ["edit", "answer", "close"],
            "permittedAttributes": ["title", "status", "assignedTo"],
            "customAttributes": {
                "priority_level": "Critical Path",
                "region": "West",
            },
        },
        {
            "id": "rfi-002-def",
            "title": "Steel Connection Detail at Node 7",
            "rfiType": "Design",
            "assignedTo": "Sarah Lee",
            "question": "The connection detail at Node 7 shows a bolted connection, but the general notes require welded connections for moment frames. Which applies?",
            "suggestedAnswer": None,
            "location": {"name": "Level 3 - Steel Frame", "details": "Node 7, Grid B-4"},
            "status": "Open",
            "officialResponse": None,
            "dueDate": "2025-03-25T00:00:00.000Z",
            "costImpact": "Yes",
            "scheduleImpact": "Yes",
            "priority": "High",
            "discipline": "Structural",
            "category": "Conflict",
            "externalId": "RFI-2025-002",
            "createdBy": "David Chen",
            "createdAt": "2025-02-15T09:00:00.000Z",
            "updatedAt": "2025-03-10T16:30:00.000Z",
            "closedAt": None,
            "postedToDrawings": False,
            "companyName": "SteelWorks Inc",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
            "permittedActions": ["edit", "answer"],
            "permittedAttributes": ["title", "status"],
            "customAttributes": {},
        },
        {
            "id": "rfi-003-ghi",
            "title": "Waterproofing Membrane Specification",
            "rfiType": "Specification",
            "assignedTo": "Emily Davis",
            "question": "The waterproofing membrane specified (Product ABC) has been discontinued. Can we use Product XYZ as a substitute?",
            "suggestedAnswer": "Product XYZ meets all performance requirements per manufacturer data sheet attached.",
            "location": {"name": "Basement Level", "details": "All exterior walls below grade"},
            "status": "Closed",
            "officialResponse": "Approved. Product XYZ is acceptable as a substitute. Submit shop drawings for review.",
            "dueDate": "2025-02-28T00:00:00.000Z",
            "costImpact": "No",
            "scheduleImpact": "No",
            "priority": "Normal",
            "discipline": "Architectural",
            "category": "Substitution",
            "externalId": "RFI-2025-003",
            "createdBy": "Tom Wilson",
            "createdAt": "2025-01-10T08:00:00.000Z",
            "updatedAt": "2025-02-20T11:00:00.000Z",
            "closedAt": "2025-02-20T11:00:00.000Z",
            "postedToDrawings": True,
            "companyName": "WaterGuard LLC",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
            "permittedActions": [],
            "permittedAttributes": [],
            "customAttributes": {},
        },
        {
            "id": "rfi-004-jkl",
            "title": "Electrical Panel Location Conflict",
            "rfiType": "Coordination",
            "assignedTo": "John Smith",
            "question": "Electrical panel EP-3A conflicts with the HVAC ductwork routing shown on M-201. Please advise on relocated position.",
            "suggestedAnswer": "Relocate panel 3 feet north along the same wall.",
            "location": {"name": "Mechanical Room 201", "details": "North wall"},
            "status": "Open",
            "officialResponse": None,
            "dueDate": "2025-05-01T00:00:00.000Z",
            "costImpact": "Yes",
            "scheduleImpact": "No",
            "priority": "Normal",
            "discipline": "MEP",
            "category": "Coordination",
            "externalId": "RFI-2025-004",
            "createdBy": "Lisa Brown",
            "createdAt": "2025-03-15T13:00:00.000Z",
            "updatedAt": "2025-03-18T09:00:00.000Z",
            "closedAt": None,
            "postedToDrawings": False,
            "companyName": "PowerUp Electric",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
            "permittedActions": ["edit", "answer"],
            "permittedAttributes": ["title", "status", "assignedTo"],
            "customAttributes": {},
        },
        {
            "id": "rfi-005-mno",
            "title": "Finish Schedule Discrepancy - Room 305",
            "rfiType": "Design",
            "assignedTo": "Sarah Lee",
            "question": "Room 305 shows ceramic tile on the floor plan but carpet on the finish schedule. Which is correct?",
            "suggestedAnswer": None,
            "location": {"name": "Level 3", "details": "Room 305"},
            "status": "Open",
            "officialResponse": None,
            "dueDate": "2025-04-10T00:00:00.000Z",
            "costImpact": "No",
            "scheduleImpact": "No",
            "priority": "Low",
            "discipline": "Architectural",
            "category": "Design Clarification, Conflict",
            "externalId": "RFI-2025-005",
            "createdBy": "Mike Johnson",
            "createdAt": "2025-03-20T15:00:00.000Z",
            "updatedAt": "2025-03-20T15:00:00.000Z",
            "closedAt": None,
            "postedToDrawings": False,
            "companyName": "ACME Builders",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
            "permittedActions": ["edit"],
            "permittedAttributes": ["title"],
            "customAttributes": {},
        },
    ],
}

# --- Submittals ---
SUBMITTALS_ITEMS_RESPONSE = {
    "pagination": {
        "limit": 100,
        "offset": 0,
        "totalResults": 4,
    },
    "results": [
        {
            "id": "sub-001-abc",
            "customIdentifier": "SUB-2025-001",
            "title": "Structural Steel Shop Drawings - Phase 1",
            "description": "Shop drawings for all structural steel members in Phase 1 area.",
            "itemType": "shop_drawing",
            "specSection": "05 12 00",
            "specSubSection": "Structural Steel Framing",
            "specNumber": "051200",
            "status": "submitted",
            "revisionNumber": 2,
            "priority": "High",
            "assignedTo": "Sarah Lee",
            "pendingActionFrom": "Reviewer",
            "personResponsibleDueDate": "2025-04-01T00:00:00.000Z",
            "packageNumber": "PKG-001",
            "packageName": "Structural Package A",
            "reviewResponses": None,
            "finalResponse": None,
            "responsibleContractor": "SteelWorks Inc",
            "manager": "John Smith",
            "reviewers": "Emily Davis, Tom Wilson",
            "distributionList": "All Team Leads",
            "sentToSubmitter": "2025-02-01T00:00:00.000Z",
            "submitterDueDate": "2025-02-15T00:00:00.000Z",
            "receivedFromSubmitter": "2025-02-14T00:00:00.000Z",
            "submitDaysOff": 0,
            "managerDueDate": "2025-03-01T00:00:00.000Z",
            "sentForReview": "2025-02-20T00:00:00.000Z",
            "receivedFromReview": None,
            "published": False,
            "requiredDate": "2025-05-01T00:00:00.000Z",
            "requiredApprovalDate": "2025-04-15T00:00:00.000Z",
            "requiredOnJobSiteDate": "2025-06-01T00:00:00.000Z",
            "leadTimeDays": 45,
            "createdAt": "2025-01-15T08:00:00.000Z",
            "createdBy": "John Smith",
            "updatedAt": "2025-03-10T10:00:00.000Z",
            "updatedBy": "Sarah Lee",
            "companyName": "SteelWorks Inc",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
        },
        {
            "id": "sub-002-def",
            "customIdentifier": "SUB-2025-002",
            "title": "Concrete Mix Design Report",
            "description": "Mix design report for 5000 PSI concrete per specification 03300.",
            "itemType": "product_data",
            "specSection": "03 30 00",
            "specSubSection": "Cast-in-Place Concrete",
            "specNumber": "033000",
            "status": "closed",
            "revisionNumber": 1,
            "priority": "Normal",
            "assignedTo": "Tom Wilson",
            "pendingActionFrom": None,
            "personResponsibleDueDate": "2025-02-01T00:00:00.000Z",
            "packageNumber": "PKG-002",
            "packageName": "Concrete Package",
            "reviewResponses": "Approved as Noted",
            "finalResponse": "Approved",
            "responsibleContractor": "ACME Builders",
            "manager": "John Smith",
            "reviewers": "Emily Davis",
            "distributionList": "Structural Team",
            "sentToSubmitter": "2025-01-05T00:00:00.000Z",
            "submitterDueDate": "2025-01-15T00:00:00.000Z",
            "receivedFromSubmitter": "2025-01-12T00:00:00.000Z",
            "submitDaysOff": 0,
            "managerDueDate": "2025-01-20T00:00:00.000Z",
            "sentForReview": "2025-01-14T00:00:00.000Z",
            "receivedFromReview": "2025-01-25T00:00:00.000Z",
            "published": True,
            "requiredDate": "2025-03-01T00:00:00.000Z",
            "requiredApprovalDate": "2025-02-15T00:00:00.000Z",
            "requiredOnJobSiteDate": "2025-03-15T00:00:00.000Z",
            "leadTimeDays": 30,
            "createdAt": "2025-01-02T09:00:00.000Z",
            "createdBy": "John Smith",
            "updatedAt": "2025-01-25T16:00:00.000Z",
            "updatedBy": "Tom Wilson",
            "companyName": "ACME Builders",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
        },
        {
            "id": "sub-003-ghi",
            "customIdentifier": "SUB-2025-003",
            "title": "HVAC Equipment Catalog Cuts",
            "description": "Product data for rooftop HVAC units RTU-1 through RTU-4.",
            "itemType": "product_data",
            "specSection": "23 74 00",
            "specSubSection": "Packaged Outdoor HVAC Equipment",
            "specNumber": "237400",
            "status": "in_review",
            "revisionNumber": 1,
            "priority": "Normal",
            "assignedTo": "Emily Davis",
            "pendingActionFrom": "Manager",
            "personResponsibleDueDate": "2025-04-10T00:00:00.000Z",
            "packageNumber": "PKG-003",
            "packageName": "Mechanical Package",
            "reviewResponses": None,
            "finalResponse": None,
            "responsibleContractor": "CoolAir Mechanical",
            "manager": "John Smith",
            "reviewers": "David Chen",
            "distributionList": "MEP Team",
            "sentToSubmitter": "2025-03-01T00:00:00.000Z",
            "submitterDueDate": "2025-03-15T00:00:00.000Z",
            "receivedFromSubmitter": "2025-03-14T00:00:00.000Z",
            "submitDaysOff": 0,
            "managerDueDate": "2025-03-25T00:00:00.000Z",
            "sentForReview": "2025-03-16T00:00:00.000Z",
            "receivedFromReview": None,
            "published": False,
            "requiredDate": "2025-06-01T00:00:00.000Z",
            "requiredApprovalDate": "2025-05-01T00:00:00.000Z",
            "requiredOnJobSiteDate": "2025-07-01T00:00:00.000Z",
            "leadTimeDays": 60,
            "createdAt": "2025-02-28T11:00:00.000Z",
            "createdBy": "Lisa Brown",
            "updatedAt": "2025-03-16T08:00:00.000Z",
            "updatedBy": "John Smith",
            "companyName": "CoolAir Mechanical",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
        },
        {
            "id": "sub-004-jkl",
            "customIdentifier": "SUB-2025-004",
            "title": "Waterproofing Membrane Sample",
            "description": "Physical sample of Product XYZ waterproofing membrane.",
            "itemType": "sample",
            "specSection": "07 10 00",
            "specSubSection": "Dampproofing and Waterproofing",
            "specNumber": "071000",
            "status": "pending",
            "revisionNumber": 1,
            "priority": "Low",
            "assignedTo": "Tom Wilson",
            "pendingActionFrom": "Submitter",
            "personResponsibleDueDate": "2025-04-20T00:00:00.000Z",
            "packageNumber": "PKG-004",
            "packageName": "Envelope Package",
            "reviewResponses": None,
            "finalResponse": None,
            "responsibleContractor": "WaterGuard LLC",
            "manager": "Sarah Lee",
            "reviewers": "John Smith",
            "distributionList": "Arch Team",
            "sentToSubmitter": "2025-03-20T00:00:00.000Z",
            "submitterDueDate": "2025-04-05T00:00:00.000Z",
            "receivedFromSubmitter": None,
            "submitDaysOff": None,
            "managerDueDate": "2025-04-15T00:00:00.000Z",
            "sentForReview": None,
            "receivedFromReview": None,
            "published": False,
            "requiredDate": "2025-07-01T00:00:00.000Z",
            "requiredApprovalDate": "2025-06-01T00:00:00.000Z",
            "requiredOnJobSiteDate": "2025-08-01T00:00:00.000Z",
            "leadTimeDays": 21,
            "createdAt": "2025-03-18T14:00:00.000Z",
            "createdBy": "Sarah Lee",
            "updatedAt": "2025-03-20T09:00:00.000Z",
            "updatedBy": "Sarah Lee",
            "companyName": "WaterGuard LLC",
            "projectId": "b.project-001",
            "projectName": "Highway Bridge Reconstruction",
        },
    ],
}

# --- Pagination example (page 2) ---
RFIS_PAGE2_RESPONSE = {
    "pagination": {
        "limit": 2,
        "offset": 2,
        "totalResults": 5,
    },
    "results": [
        RFIS_SEARCH_RESPONSE["results"][2],
        RFIS_SEARCH_RESPONSE["results"][3],
    ],
}
